### ISSUE TITLE
Step 4 of Wetland Inventory workflow has issues with the shape file

### ISSUE THREAD

**Issue by j08lue** [GlobWetlandAfrica/GWA_models_and_workflows#22]
Step 4 of the Wetland Inventory workflow takes a shape file for cropping. It is formally not required, but the model fails if it is omitted.

Furthermore, when the raster is clipped, it is not cropped but the clipped area is just filled with NaN. This is fixed with https://github.com/GlobWetlandAfrica/GWA_models_and_workflows/commit/d2ca869d81309b6923436885cbc04bfe63b83343

The model should either not require a shape file at all or at least not fail when it gets one.

**Comment by redfrexx** [comment]
The shapefile should be provided, it was just not set to "required" in the model. I will change that parameter in the model.

**Comment by j08lue** [comment]
> I will change that parameter in the model.

I changed that in https://github.com/GlobWetlandAfrica/GWA_models_and_workflows/commit/32a9236e2430634282b9b25cbd9c794b2631e729
