### ISSUE TITLE
Python issue

### ISSUE THREAD

**Issue by ctottrup** [GlobWetlandAfrica/GWA_models_and_workflows#23]
upon finishing step 3 under the workflow "indices calculation and texture extraction"  QGIS reports "python.exe has stopped working", yet the output seem to be okay and work can be continued after closing the error window - we experience this issue also for step 5 in the workflow Wetland Habitat Historical mapping (with change mask)

**Comment by j08lue** [comment]
This is probably the same as #8 - and should be fixed with an update.
