### ISSUE TITLE
Missing model `mm_s2_moisture`

### ISSUE THREAD

**Issue by j08lue** [GlobWetlandAfrica/GWA_models_and_workflows#29]
## Problem

In https://github.com/GlobWetlandAfrica/GWA_models_and_workflows/commit/6c8f2efe8e914524bc6d843101c2fa0027a57e64, @floinn removed a model that is required for the **Mangroves Extent** workflow:

https://github.com/GlobWetlandAfrica/GWA_models_and_workflows/blob/4f027e210cff814850256b07b87b0741646a661c/workflows/GWA_TBX/06_MM_extent.workflow#L138

We still have this other `s2_moisture` model, but it seems to be different:

https://github.com/GlobWetlandAfrica/GWA_models_and_workflows/blob/39c01871b610311a51a6fcd0790651bce94d9652/models/GWA_TBX/S2_moisture.model

## Question

Why did @floinn remove the `mm_s2_moisture` model? Is `s2_moisture` supposed to replace it? If so, please fix the `06_MM_extent.workflow` accordingly.

**Comment by j08lue** [comment]
Meant to be fixed in #30 and #31. Waiting for confirmation.

**Comment by floinn** [comment]
@j08lue: mm_s2_moisture was replaced by MM_S2_NDII 24 days ago, but the workflow didn't change accordingly. The current 06_MM_extent.workflow is the correct one and all models should be implemented. Sorry for the inconveniences...

**Comment by j08lue** [comment]
That happens 😄 thanks for the fix, @floinn.
