### ISSUE TITLE
Sentinel downloader only finds S1 scenes

### ISSUE THREAD

**Issue by ctottrup** [GlobWetlandAfrica/GWA_models_and_workflows#33]

**Comment by j08lue** [comment]
I am able to reproduce this issue. Sorry about that. Fix coming up.

**Comment by j08lue** [comment]
Fixed with https://github.com/sentinelsat/sentinelsat-qgis-script/pull/7

and

https://github.com/TIGER-NET/WOIS_scripts/commit/f32cef604f128975a8b131f92875530cfa743090

**Comment by j08lue** [comment]
Fixed.
