### ISSUE TITLE
Search & Download Sentinel data 401 Unauthorized

### ISSUE THREAD

**Issue by HerrKaha** [GlobWetlandAfrica/GWA_models_and_workflows#35]
I just installed the toolbox and started playing around with it and I run into a issue while looking for some sentinel data.

After filling out the search parameters and hitting run I get this error message:
Algorithm Download Sentinel starting...

HTTP status 401 Unauthorized: # HTTP Status 401 - Full authentication is required to access this resource **type** Status report **message** _Full authentication is required to access this resource_ **description** _This request requires HTTP authentication._ * * * ### Apache Tomcat/8.0.36 See log for more details

My username and password work when I log in to https://scihub.copernicus.eu/dhus on a web browser, I even tried to copy and paste the same text to make sure I didn't make any typos.

**Comment by j08lue** [comment]
Thanks for reporting this @HerrKaha. 

Could it be that you created your account very recently? It may take a while before the SciHub access also works for the API access that our QGIS / Python tool uses.

See https://github.com/sentinelsat/sentinelsat/issues/188

Please try, like in the proposed solution to the `sentinelsat` issue, to use `https://scihub.copernicus.eu/dhus` as DHuS URL.

**Comment by HerrKaha** [comment]
Thanks for the quick reply!
Yes I created my account on Monday. I'll wait and let you know when it starts working.

**Comment by HerrKaha** [comment]
Forgot to mention if I change the /apihub endpoint to /dhus in the advanced parameters then it works.

**Comment by j08lue** [comment]
Thanks for the information. Please also report when your account starts working against /dhus.

**Comment by HerrKaha** [comment]
Tried the workflow again today and it worked with the default /apihub endpoint now. Didn't try yesterday but the day before that it still didn't work. So it took about 10-11 days.
