### ISSUE TITLE
Image stacking - band ordering

### ISSUE THREAD

**Issue by ctottrup** [GlobWetlandAfrica/GWA_models_and_workflows#42]
It is difficult to get the band order correct when doing image stacking either with gdal merge or built VRT (cf. Landsat pre-processing) - it does not always help reordering in the layers panel . Should have been solved with QGIS 3.0 - but is there a work around for QGIS 2.XX?

**Comment by radosuav** [comment]
Should be solved now with [with a recent commit to WOIS_processing](https://github.com/TIGER-NET/WOIS_processing/commit/c92ada8d8745bd92cc8f1f2ba413595de88524d9). The layers can now be reordered by dragging-and-dropping in the selection panel.
