### ISSUE TITLE
Step 1 in Budyko model, merge and warp, fails

### ISSUE THREAD

**Issue by KittelC** [GlobWetlandAfrica/GWA_models_and_workflows#54]
Is it correct that this step will only work in QGIS 3 because of the "ParameterMultipleInput"? In that case, maybe it would be nice to add a warning in the workflow text, so that users skip it and "merge and warp" their DEM manually if still working in QGIS 2..

**Comment by j08lue** [comment]
The GWA Toolbox will not be updated from QGIS 2.18 to QGIS 3 within the current project, so I don't think this is intended. What do you think @radosuav?

**Comment by radosuav** [comment]
It should work with QGIS 2 and has not been tested with QGIS 3. @KittelC how does it fail? In QGIS 2 the images have to be loaded into the canvas before they can be selected using ParameterMultipleInput. Is this the issue?

**Comment by KittelC** [comment]
I get the error "IndexError: list index out of range". All images were loaded into the canvas beforehand, so it is not related to that. I tried with 2, 3 and 4 images as well without luck.

**Comment by radosuav** [comment]
Hmm.. I will investigate tomorrow.

**Comment by KittelC** [comment]
Thank you! I also get another error in step 5 - Process catchment layers "
Error executing algorithm Clean-up stream and catchment vectors 'QgsVectorLayer' object has no attribute 'changeAttributeValues' See log for more details" (there is not a lot more information in the log: "

2019-01-14T15:06:16	1	Traceback (most recent call last):
			  File "C:/Users/ceki/.qgis2/python/plugins\profiletool\apicompat\qgsmaplayer.py", line 10, in isSpatial
			    return self.hasGeometryType()
			AttributeError: 'QgsRasterLayer' object has no attribute 'hasGeometryType' " 

I can open another issue, but I figured, since they are in the same workflow it would be ok to keep them together.

**Comment by KittelC** [comment]
So error #55 is indeed fixed by updating, but now this step produces a single tiny pixel or an empty raster... all my tiles are in lat-lon projection and I have checked that I am using the right UTM projection.

**Comment by radosuav** [comment]
Do you set the extent or leave it blank? If you tiles are in lat-lon but you are reprojecting to UTM then leaving the extent blank will not work. You need to either draw the extent on canvas (in which case the canvas projection should be in the same UTM zone as the one you are reprojecting to) or use an extent of existing layer (this layer should be in the same UTM zone as the one you are projecting to).

In QGIS 3 the handling to layers with different projecting in Processing should be more elegant.

**Comment by KittelC** [comment]
I see. However, the extent only lets me select the extent in the original files' projection (so in degrees), unless I first change the project CRS. The files have to be reprojected for TauDEM to run, so I am not sure how the user would be able to work around this, when starting out with just the SRTM tiles... It also still doesn't work, if I leave the resolution option blank. I guess for the same reason, but it is misleading when it says "(leave as 0 for no change)".

I think the default information are a misleading for this step, as they suggest the spatial extent and resolution are optional arguments - perhaps we need a bit better default values/guidance?

**Comment by KittelC** [comment]
(I also get an extent CRS warning about the extent parameters having a different CRS than the input layers...)

**Comment by radosuav** [comment]
True, that could be confusing for the users. What do you think about the change in https://github.com/DHI-GRAS/budyko-qgis/commit/f6931ac10fbbc5dad7754b0c4ddf6abdbc637d7d ? If the user is working with SRTM files in lat-lon projection and leaves all the options with default values (i.e. spatial extent as blank and resolution as 0) then all the input SRTM tiles are merged and reprojected. If only a subset is required then the extent can be specified on canvas and the "Coordinate system of the extent" should be set to the canvas projection.

**Comment by KittelC** [comment]
That works! Feels clearer as well :-) (and runs much faster for some reason... )

**Comment by radosuav** [comment]
Nice :) Can I close the issue?

**Comment by KittelC** [comment]
Yes, I think we can close it, at least on my machine, it is fixed ;-)
