### ISSUE TITLE
python error - water mask model

### ISSUE THREAD

**Issue by ctottrup** [GlobWetlandAfrica/GWA_models_and_workflows#8]
upon finishing the water mask model qgis reports "python.exe has stopped working", yet the output seem to be okay and work can be continued after closing the error window.

**Comment by j08lue** [comment]
If that is okay with you, we can debug that further when you are back.

**Comment by j08lue** [comment]
This is probably a GDAL bug I have seen discussed quite a lot. It might go away with an update to the newest OSGeo packages.

**Comment by redfrexx** [comment]
I haven't encountered this error lately, but I'll look into it again.

**Comment by j08lue** [comment]
@redfrexx Don't worry about this. I think it is a GDAL thing and will go away when we update the packages.
