### ISSUE TITLE
wrapped C/C++ object of type QTextEdit has been deleted in Export Sentinel-2 data

### ISSUE THREAD

**Issue by vlro** [GlobWetlandAfrica/GWA_models_and_workflows#9]
The export sentinel-2 data step in the Sentinel-2 Pre-processing workflow works fine the first time it is run in QGIS. However, when trying to run again for a second image, the process does not start and the following message is displayed:

wrapped C/C++ object of type QTextEdit has been deleted See log for more details

Restarting QGIS  allows the step to be run again for one image.

 The issue doesn't appear when running the individual algorithm, it only appears when running the algorithm from the Sentinel-2 Pre-processing workflow in the GlobWetlandAfrica toolbox.

**Comment by j08lue** [comment]
This might come from these lines: https://github.com/DHI-GRAS/QGIS_s2_export/blob/e11f88a7b08a9c35a08102df8022fcdcb3a1c291/qgis_s2_export.py#L74-L75

It might help to make loading the output files an option that you can turn off when running in batch mode.

To test, please try to comment out these two lines in `~/.qgis2/processing/scripts/sentinel_scripts/s2_export/qgis_s2_export.py` (or similar). Perhaps restart QGIS after the change, I don't know if the script files are somehow cached when run in batch mode.
